/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MainController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.BenhAn;
import model.Buong;

/**
 *
 * @author HoaiNam
 */
public class MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm
     */
    private Buong buongKham;
    private List<BenhAn> dsBA;
    private DefaultTableModel modelBN;

    public MainFrm() {
        initComponents();
        // MainFrm của phòng khám có ID = 1.
        buongKham = new Buong(1, "Phong Kham 01", "201-A1", "Phong Kham");
        dsBA = new ArrayList<>();
        modelBN = (DefaultTableModel) tbl_DSBA.getModel();

        // xét tên cho buồng khám.
        lab_tenBuong.setText(buongKham.getTen());

        // Khởi tạo FramKham. -> đẩy theo đối tượng bệnh án.
        MainController mainCtr = new MainController();
        dsBA = mainCtr.getDSBenhAnCho(buongKham.getId());
        drawBA(dsBA);
    }

    private void drawBA(List<BenhAn> dsBA) {
        // Xóa các row.
        while (modelBN.getRowCount() > 0) {
            modelBN.removeRow(0);
        }
        
        int i = 1;
        
        for (BenhAn bn : dsBA) {
            modelBN.addRow(new Object[]{
                i++,
                bn.getBenhNhan().getTen(),
                bn.getBenhNhan().getTuoi(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lab_tenBuong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSBA = new javax.swing.JTable();
        btn_capNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Buồng Khám : ");

        lab_tenBuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_tenBuong.setText("204 - Tai Mũi Họng");

        jLabel5.setText("Danh sách bệnh nhân đang chờ khám ");

        tbl_DSBA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Bệnh Nhân", "Tuổi"
            }
        ));
        tbl_DSBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DSBAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DSBA);

        btn_capNhap.setText("Cập nhập");
        btn_capNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lab_tenBuong)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btn_capNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lab_tenBuong))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_capNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_DSBAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DSBAMouseClicked
        // TODO add your handling code here:
        int selected = tbl_DSBA.getSelectedRow();
        BenhAn ba = dsBA.get(selected);
        KhamFrm kham = new KhamFrm(ba);
        kham.setVisible(true);
    }//GEN-LAST:event_tbl_DSBAMouseClicked

    private void btn_capNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhapActionPerformed
        // TODO add your handling code here:
        MainController mainCtr = new MainController();
        dsBA = mainCtr.getDSBenhAnCho(buongKham.getId());
        drawBA(dsBA);
    }//GEN-LAST:event_btn_capNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_tenBuong;
    private javax.swing.JTable tbl_DSBA;
    // End of variables declaration//GEN-END:variables

}
